// export type Ticket = {
//     id: number;
//     code: number;
//     status: boolean;
//     hora_solicitacao: string;
//     aberto_por: string;
//     categoria: string;
//     sub_categoria: string;
//     titulo: string;
//     usuario_solicitante: string;
//     administrador_do_grupo: string;
//     atendente: string;
//     prioridade: string;
//     data_para_conclusao: string;
//     tempo_de_atendimento: string;
// }
export type Ticket = {
  id: number;
  problem_type: string;
  problem_sub_type: string;
  title: string;
  description: string;
  status: number;
  responsibility: string;
  urgency: number;
  priority: number;
  notes: string;
  resolution: string;
  solution: string;
  insert_time: string;
  update_time: string;
  close_time: string | null;
  update_user: string;
  submit_user: string;
  request_user: string;
  third_level_category: string;
  assigned_group: string;
  timer1: number;
  timer2: number;
  timer3: number;
  timer4: number | null;
  timer6: number | null;
  sr_type: number;
  sr_sub_type: number;
  impact: number;
  version: number;
  sr_cust_agendamento: string;
  sr_cust_anotacao_tec: string;
  sr_cust_cadastro_ponto: number;
  sr_cust_colaborador: string;
  sr_cust_data_agendada: string | null;
  sr_cust_divulgacao_vaga: number;
  sr_cust_entrega_doc: number;
  sr_cust_entrevista_gest: number;
  sr_cust_entrevista_rh: number;
  sr_cust_envio_doc: number;
  sr_cust_hora_agendada: string;
  sr_cust_proj_contrato: string;
  sr_cust_solicita_comput: number;
  sr_cust_solicita_email: number;
  sr_cust_solicita_login: number;
  sr_cust_telefone: string;
  sr_cust_treino_welcome: number;
  sr_cust_tria_curriculos: number;
}